### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by alalaha** [Spiderjockey02/auto-poster-and-notifications#30]
Why when I modify the channel through the database it has no effect on the bot? I have to reboot for the channel to be changed...

**Comment by GoldenCredit101** [comment]
come to the support server for further assistance...

**Comment by Spiderjockey02** [comment]
Can u tell me more information like what service you were using (twitter, reddit etc)

**Comment by alalaha** [comment]
Twitter

> Can u tell me more information like what service you were using (twitter, reddit etc)

**Comment by alalaha** [comment]
hi

**Comment by GoldenCredit101** [comment]
> hi

Yes?

**Comment by Spiderjockey02** [comment]
I'm on holiday so I can't check the code

**Comment by alalaha** [comment]
Did you check the code? any news?

**Comment by Spiderjockey02** [comment]
I'll check/fix it tonight

**Comment by alalaha** [comment]
> I'll check/fix it tonight (UK time)

Ok! Thank you

**Comment by alalaha** [comment]
found the problem @Spiderjockey02 ?

**Comment by alalaha** [comment]
hello?

**Comment by alalaha** [comment]
?????????

**Comment by GoldenCredit101** [comment]
Please join support for assistance https://discord.gg/QMt3TXke

**Comment by alalaha** [comment]
sad

**Comment by Spiderjockey02** [comment]
sorry for the wait being busy with life things, it should be fixed now

**Comment by alalaha** [comment]
Not fixed, channel change still only takes effect when restart the bot

**Comment by alalaha** [comment]
will you fix this someday?

**Comment by StudNastty** [comment]
> will you fix this someday?

You can look into the code yourself to try to fix the issue
